export const ActionTypes = {
  // SET_VEHICLES: "SET_VEHICLES",
  // SELECTED_VEHICLE: "SELECTED_VEHICLE",
  GET_VEHICLES: 'GET_VEHICLES',
  GET_VEHICLES_SUCCESS: 'GET_VEHICLES_SUCCESS',
  GET_VEHICLES_FAILURE: 'GET_VEHICLES_FAILURE'
};

export const VehicleStatus = {
  AVAILABLE: 0,
  BOOKED: 1,
  ALERT_BATTERY: 2,
  ALERT_GPS: 3,
  MAINTENANCE: 4,
  DISABLED: 5,
  TOW: 6,
};